version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Running npm install
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
      - pwd
      - bash VersionChange.sh
      - pwd
      - npm run build-reference-app
      - echo "Build completed on `date`"
  post_build:
    commands:
      - pwd
      - cd dist
      - echo "Deploying to $DEST_BUCKET"
      - aws s3 sync --delete instnt-angular s3://$DEST_BUCKET
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths '/*'
      


